server:
  port: 8080
  shutdown: graceful


spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s # For Graceful Shutdown
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:example_db?serverTimezone=UTC&characterEncoding=UTF-8&mode=mysql
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:/db/migration


  h2:
    console:
      enabled: true
